apiVersion: batch/v1beta1
kind: Job
metadata:
  name: restore-kubectl-test
spec:
  template:
    spec:
      serviceAccount: internal-kubectl
      restartPolicy: OnFailure
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command: ["kubectl"]
        # Replace "deployment" in the pod name with the name of your helm deployment
        args: ["exec", "-ti", "deployment-pingdirectory-0", "--container", "pingdirectory-utility", "--", "/opt/in/restore.sh"]