#######################################################################
# Ping Identity DevOps Chart
########################################################################
apiVersion: v2
name: ping-devops
########################################################################
# 0.12.1 - Refer to http://helm.pingidentity.com/release-notes/currentRelease
########################################################################
version: 0.12.1
description: Ping Identity helm charts - April 1, 2026
type: application
home: https://helm.pingidentity.com/
icon: https://helm.pingidentity.com/img/logos/ping.png
appVersion: "2603"
