{{- include "pinglib.workload" (list . "pingfederate-admin") -}}



{{- define "pingfederate-admin.workload" -}}
spec:
  template:
    metadata:
      labels:
        clusterIdentifier: {{ include "pinglib.fullimagename" . }}
{{- end -}}
