{{- include "pinglib.configmap" (list . "global") -}}



{{- define "global.configmap" -}}
{{- $top := index . 0 -}}
{{- $v := index . 1 -}}
data:
  {{/* Remove the pingaccess when we move to an engine/admin */}}
  {{ include "global.configmap.env.hostname" (list $top $v "PA_ENGINE_PRIVATE_HOSTNAME" "pingaccess") }}
  {{ include "global.configmap.env.hostname" (list $top $v "PA_ENGINE_PRIVATE_HOSTNAME" "pingaccess-engine") }}
  {{ include "global.configmap.env.hostname" (list $top $v "PA_ADMIN_PRIVATE_HOSTNAME" "pingaccess-admin") }}
  {{ include "global.configmap.env.hostname" (list $top $v "PDS_ENGINE_PRIVATE_HOSTNAME" "pingdatasync") }}
  {{ include "global.configmap.env.hostname" (list $top $v "PDG_ENGINE_PRIVATE_HOSTNAME" "pingdatagovernance") }}
  {{ include "global.configmap.env.hostname" (list $top $v "PDGP_ENGINE_PRIVATE_HOSTNAME" "pingdatagovernancepap") }}
  {{ include "global.configmap.env.hostname" (list $top $v "PD_DELEGATOR_PRIVATE_HOSTNAME" "pingdelegator") }}
  {{ include "global.configmap.env.hostname" (list $top $v "PD_ENGINE_PRIVATE_HOSTNAME" "pingdirectory") }}
  {{ include "global.configmap.env.hostname" (list $top $v "PDP_ENGINE_PRIVATE_HOSTNAME" "pingdirectoryproxy") }}
  {{ include "global.configmap.env.hostname" (list $top $v "PF_ENGINE_PRIVATE_HOSTNAME" "pingfederate-engine") }}
  {{ include "global.configmap.env.hostname" (list $top $v "PF_ADMIN_PRIVATE_HOSTNAME" "pingfederate-admin") }}

  {{/* Remove the pingaccess when we move to an engine/admin */}}
  {{ include "global.configmap.env.ingress.hostname" (list $top $v "PA_ENGINE_PUBLIC_HOSTNAME" "pingaccess") }}
  {{ include "global.configmap.env.ingress.hostname" (list $top $v "PA_ENGINE_PUBLIC_HOSTNAME" "pingaccess-engine") }}
  {{ include "global.configmap.env.ingress.hostname" (list $top $v "PA_ADMIN_PUBLIC_HOSTNAME" "pingaccess-admin") }}
  {{ include "global.configmap.env.ingress.hostname" (list $top $v "PDS_ENGINE_PUBLIC_HOSTNAME" "pingdatasync") }}
  {{ include "global.configmap.env.ingress.hostname" (list $top $v "PDG_ENGINE_PUBLIC_HOSTNAME" "pingdatagovernance") }}
  {{ include "global.configmap.env.ingress.hostname" (list $top $v "PDGP_ENGINE_PUBLIC_HOSTNAME" "pingdatagovernancepap") }}
  {{ include "global.configmap.env.ingress.hostname" (list $top $v "PD_DELEGATOR_PUBLIC_HOSTNAME" "pingdelegator") }}
  {{ include "global.configmap.env.ingress.hostname" (list $top $v "PD_ENGINE_PUBLIC_HOSTNAME" "pingdirectory") }}
  {{ include "global.configmap.env.ingress.hostname" (list $top $v "PDP_ENGINE_PUBLIC_HOSTNAME" "pingdirectoryproxy") }}
  {{ include "global.configmap.env.ingress.hostname" (list $top $v "PF_ENGINE_PUBLIC_HOSTNAME" "pingfederate-engine") }}
  {{ include "global.configmap.env.ingress.hostname" (list $top $v "PF_ADMIN_PUBLIC_HOSTNAME" "pingfederate-admin") }}
{{- end -}}


{{- define "global.configmap.env.hostname" -}}
{{- $top := index . 0 }}
{{- $v := index . 1 }}
{{- $envName := index . 2 }}
{{- $prodName := index . 3 }}
{{- with (index $top.Values $prodName) }}
{{- if .enabled }}
  {{ $envName }}: {{ include "pinglib.addreleasename" (list $top $v .name) | quote }}
{{- end }}
{{- end }}
{{- end -}}

{{- define "global.configmap.env.ingress.hostname" -}}
{{- $top := index . 0 }}
{{- $v := index . 1 }}
{{- $envName := index . 2 }}
{{- $prodName := index . 3 }}
{{- with (index $top.Values $prodName) }}
{{- if and .enabled .ingress.enabled }}
{{- range .ingress.hosts }}
  {{ $envName }}: {{ include "pinglib.ingress.hostname" (list $top $v .host) | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}