# This test covers emptyDir fallback volume creation for a Deployment utility sidecar.

### SECTION:PARAMETERS ###
releaseName: utility-sidecar-deployment-volumes
skipTest: false
### SECTION:VALUES ###
pingdataconsole:
  enabled: true
  utilitySidecar:
    enabled: true
### SECTION:EXPECTED ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-sidecar-deployment-volumes-pingdataconsole
spec:
  template:
    spec:
      containers:
        - name: utility-sidecar
          volumeMounts:
            - name: out-dir
              mountPath: /opt/out
            - name: temp
              mountPath: /tmp
      volumes:
        - name: temp
          emptyDir: {}
        - name: out-dir
          emptyDir: {}
