{{- include "pinglib.workload" (list . "pingdirectory") -}}



{{- define "pingdirectory.workload" -}}
spec:
  template:
    metadata:
      labels:
        clusterIdentifier: {{ include "pinglib.fullimagename" . }}
{{- end -}}