{{- include "pinglib.workload" (list . "pingfederate-engine") -}}


{{- define "pingfederate-engine.workload" -}}
spec:
  template:
    metadata:
      labels:
        clusterIdentifier: {{ include "pinglib.fullimagename" . }}
{{- end -}}


