{{- include "pinglib.workload" (list . "pingaccess-admin") -}}


{{- define "pingaccess-admin.workload" -}}
spec:
  template:
    metadata:
      labels:
        clusterIdentifier: {{ include "pinglib.addreleasename" (append . "pingaccess") }}
{{- end -}}